kind: Service
apiVersion: v1
metadata:
  name: nginx-html
spec:
  selector:
    app: nginx-html
  type: NodePort
  ports:
    - protocol: TCP
      port: 30097
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-html
  labels:
    app: nginx-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-html
  template:
    metadata:
      labels:
        app: nginx-html
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nginx-html
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
